### ISSUE TITLE
There is a problem with clustered location markers disappearing.

### ISSUE THREAD

**Issue by galaxy821** [CAU23-Capstone-Design/client#2] opened 2023-05-30 08:31 UTC
There is a problem that the markers disappear when separate location markers after cluster markers in Google Maps screen

**Comment by KmYongHwan** [comment] 2023-06-01 21:52
This issue was caused by clusterrenderer's getBucket function, and bug is resolved by modifying the getBucket logic.

**Closed as completed by KmYongHwan** 2023-06-01 21:52 UTC
Labels: bug
